# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14931cbe8871c5b62354d0674fa946000144c483684c58d80d11c24ce1d4fe64b8b79786b8732969e004f39f409a631a4f1408321594c73ef7dca84db736ab1e

test:
  secret_key_base: 709b703b210c07c410f1b534155f19d6255c26f348ada2707ca728c379540b2554eb6255af06664c1de5f41920798e3246f2798c039b7259cee679da351ac50c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
